name: Provision Sonar Project

on:
  repository_dispatch:
    types: [create-service]

jobs:
  create-sonar-project:
    runs-on: ubuntu-latest

    steps:
      - name: Create SonarCloud project
        run: |
          curl -u $SONAR_TOKEN: \
            -X POST "https://sonarcloud.io/api/alm_integrations/import_github_repository" \
            -d "organization=alex-holanda" \
            -d "repositoryKey=${{ github.event.client_payload.repo }}"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}